In [2]:
from sklearn.linear_model import LinearRegression, Ridge, RidgeCV, Lasso, LassoCV
from sklearn.metrics import mean_absolute_error, mean_squared_error
import pandas as pd
import numpy as np

In [ ]:
# 0.5 0.5 0.7 1500  1658.1
# 0.5 0.5 0.8 1500  1556.5
# 0.5 0.5 0.6 1500  1677.3
# 0.5 0.5 0.7 16    1929
# 0.5 0.5 0.7 2000  1654.8
# 0.5 0.5 0.7 1000  1649.1
# 0.5 0.5 0.7 800   1663.7
# 0.5 0.6 0.7 1500  1628.1
# 0.6 0.5 0.8 1500  1613.2
# 0.5 0.6 0.8 1500  1668.6
# 0.5 0.9 0.4 1500  1687.4
# 0.5 0.7 0.4 1500  1666.7
# 0.5 0.4 0.8 1500  1602.2
# 0.6 0.6 0.8 1500  1628.1

In [3]:
d = dict()
d['theta'] = [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.6, 0.5, 0.5, 0.5, 0.5, 0.6, 0.6, 0.04, 0.84]
d['alpha'] = [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.6, 0.5, 0.6, 0.9, 0.7, 0.4, 0.6, 0.4, 0.4, 0.47]
d['beta'] = [0.7, 0.8, 0.6, 0.7, 0.7, 0.7, 0.7, 0.7, 0.8, 0.8, 0.4, 0.4, 0.8, 0.8, 0.7, 0.96, 0.94]
d['parts'] = [1500, 1500, 1500, 16, 2000, 1000, 800, 1500, 1500, 1500, 1500, 1500, 1500, 1500, 1500, 1500, 1500]

d['results'] = [1658.1, 1556.5, 1677.3, 1929, 1654.8, 1649.1, 1663.7, 1628.1, 1613.2, 1668.6, 1687.4, 1666.7, 1602.2, 1628.1, 1621.6, 1634.3, 1706.7]

df = pd.DataFrame(data=d)
df

    theta  alpha  beta  parts  results
0    0.50   0.50  0.70   1500   1658.1
1    0.50   0.50  0.80   1500   1556.5
2    0.50   0.50  0.60   1500   1677.3
3    0.50   0.50  0.70     16   1929.0
4    0.50   0.50  0.70   2000   1654.8
5    0.50   0.50  0.70   1000   1649.1
6    0.50   0.50  0.70    800   1663.7
7    0.50   0.60  0.70   1500   1628.1
8    0.60   0.50  0.80   1500   1613.2
9    0.50   0.60  0.80   1500   1668.6
10   0.50   0.90  0.40   1500   1687.4
11   0.50   0.70  0.40   1500   1666.7
12   0.50   0.40  0.80   1500   1602.2
13   0.60   0.60  0.80   1500   1628.1
14   0.60   0.40  0.70   1500   1621.6
15   0.04   0.40  0.96   1500   1634.3
16   0.84   0.47  0.94   1500   1706.7

In [4]:
X = df.iloc[:, :-1] 
y = df['results']
print(X, y)

    theta  alpha  beta  parts
0    0.50   0.50  0.70   1500
1    0.50   0.50  0.80   1500
2    0.50   0.50  0.60   1500
3    0.50   0.50  0.70     16
4    0.50   0.50  0.70   2000
5    0.50   0.50  0.70   1000
6    0.50   0.50  0.70    800
7    0.50   0.60  0.70   1500
8    0.60   0.50  0.80   1500
9    0.50   0.60  0.80   1500
10   0.50   0.90  0.40   1500
11   0.50   0.70  0.40   1500
12   0.50   0.40  0.80   1500
13   0.60   0.60  0.80   1500
14   0.60   0.40  0.70   1500
15   0.04   0.40  0.96   1500
16   0.84   0.47  0.94   1500 0     1658.1
1     1556.5
2     1677.3
3     1929.0
4     1654.8
5     1649.1
6     1663.7
7     1628.1
8     1613.2
9     1668.6
10    1687.4
11    1666.7
12    1602.2
13    1628.1
14    1621.6
15    1634.3
16    1706.7
Name: results, dtype: float64

In [11]:
alphas = np.arange(2.5, 3, 0.0005)
alphas

array([2.5   , 2.5005, 2.501 , 2.5015, 2.502 , 2.5025, 2.503 , 2.5035,
       2.504 , 2.5045, 2.505 , 2.5055, 2.506 , 2.5065, 2.507 , 2.5075,
       2.508 , 2.5085, 2.509 , 2.5095, 2.51  , 2.5105, 2.511 , 2.5115,
       2.512 , 2.5125, 2.513 , 2.5135, 2.514 , 2.5145, 2.515 , 2.5155,
       2.516 , 2.5165, 2.517 , 2.5175, 2.518 , 2.5185, 2.519 , 2.5195,
       2.52  , 2.5205, 2.521 , 2.5215, 2.522 , 2.5225, 2.523 , 2.5235,
       2.524 , 2.5245, 2.525 , 2.5255, 2.526 , 2.5265, 2.527 , 2.5275,
       2.528 , 2.5285, 2.529 , 2.5295, 2.53  , 2.5305, 2.531 , 2.5315,
       2.532 , 2.5325, 2.533 , 2.5335, 2.534 , 2.5345, 2.535 , 2.5355,
       2.536 , 2.5365, 2.537 , 2.5375, 2.538 , 2.5385, 2.539 , 2.5395,
       2.54  , 2.5405, 2.541 , 2.5415, 2.542 , 2.5425, 2.543 , 2.5435,
       2.544 , 2.5445, 2.545 , 2.5455, 2.546 , 2.5465, 2.547 , 2.5475,
       2.548 , 2.5485, 2.549 , 2.5495, 2.55  , 2.5505, 2.551 , 2.5515,
       2.552 , 2.5525, 2.553 , 2.5535, 2.554 , 2.5545, 2.555 , 2.5555,
       2.556 , 2.5565, 2.557 , 2.5575, 2.558 , 2.5585, 2.559 , 2.5595,
       2.56  , 2.5605, 2.561 , 2.5615, 2.562 , 2.5625, 2.563 , 2.5635,
       2.564 , 2.5645, 2.565 , 2.5655, 2.566 , 2.5665, 2.567 , 2.5675,
       2.568 , 2.5685, 2.569 , 2.5695, 2.57  , 2.5705, 2.571 , 2.5715,
       2.572 , 2.5725, 2.573 , 2.5735, 2.574 , 2.5745, 2.575 , 2.5755,
       2.576 , 2.5765, 2.577 , 2.5775, 2.578 , 2.5785, 2.579 , 2.5795,
       2.58  , 2.5805, 2.581 , 2.5815, 2.582 , 2.5825, 2.583 , 2.5835,
       2.584 , 2.5845, 2.585 , 2.5855, 2.586 , 2.5865, 2.587 , 2.5875,
       2.588 , 2.5885, 2.589 , 2.5895, 2.59  , 2.5905, 2.591 , 2.5915,
       2.592 , 2.5925, 2.593 , 2.5935, 2.594 , 2.5945, 2.595 , 2.5955,
       2.596 , 2.5965, 2.597 , 2.5975, 2.598 , 2.5985, 2.599 , 2.5995,
       2.6   , 2.6005, 2.601 , 2.6015, 2.602 , 2.6025, 2.603 , 2.6035,
       2.604 , 2.6045, 2.605 , 2.6055, 2.606 , 2.6065, 2.607 , 2.6075,
       2.608 , 2.6085, 2.609 , 2.6095, 2.61  , 2.6105, 2.611 , 2.6115,
       2.612 , 2.6125, 2.613 , 2.6135, 2.614 , 2.6145, 2.615 , 2.6155,
       2.616 , 2.6165, 2.617 , 2.6175, 2.618 , 2.6185, 2.619 , 2.6195,
       2.62  , 2.6205, 2.621 , 2.6215, 2.622 , 2.6225, 2.623 , 2.6235,
       2.624 , 2.6245, 2.625 , 2.6255, 2.626 , 2.6265, 2.627 , 2.6275,
       2.628 , 2.6285, 2.629 , 2.6295, 2.63  , 2.6305, 2.631 , 2.6315,
       2.632 , 2.6325, 2.633 , 2.6335, 2.634 , 2.6345, 2.635 , 2.6355,
       2.636 , 2.6365, 2.637 , 2.6375, 2.638 , 2.6385, 2.639 , 2.6395,
       2.64  , 2.6405, 2.641 , 2.6415, 2.642 , 2.6425, 2.643 , 2.6435,
       2.644 , 2.6445, 2.645 , 2.6455, 2.646 , 2.6465, 2.647 , 2.6475,
       2.648 , 2.6485, 2.649 , 2.6495, 2.65  , 2.6505, 2.651 , 2.6515,
       2.652 , 2.6525, 2.653 , 2.6535, 2.654 , 2.6545, 2.655 , 2.6555,
       2.656 , 2.6565, 2.657 , 2.6575, 2.658 , 2.6585, 2.659 , 2.6595,
       2.66  , 2.6605, 2.661 , 2.6615, 2.662 , 2.6625, 2.663 , 2.6635,
       2.664 , 2.6645, 2.665 , 2.6655, 2.666 , 2.6665, 2.667 , 2.6675,
       2.668 , 2.6685, 2.669 , 2.6695, 2.67  , 2.6705, 2.671 , 2.6715,
       2.672 , 2.6725, 2.673 , 2.6735, 2.674 , 2.6745, 2.675 , 2.6755,
       2.676 , 2.6765, 2.677 , 2.6775, 2.678 , 2.6785, 2.679 , 2.6795,
       2.68  , 2.6805, 2.681 , 2.6815, 2.682 , 2.6825, 2.683 , 2.6835,
       2.684 , 2.6845, 2.685 , 2.6855, 2.686 , 2.6865, 2.687 , 2.6875,
       2.688 , 2.6885, 2.689 , 2.6895, 2.69  , 2.6905, 2.691 , 2.6915,
       2.692 , 2.6925, 2.693 , 2.6935, 2.694 , 2.6945, 2.695 , 2.6955,
       2.696 , 2.6965, 2.697 , 2.6975, 2.698 , 2.6985, 2.699 , 2.6995,
       2.7   , 2.7005, 2.701 , 2.7015, 2.702 , 2.7025, 2.703 , 2.7035,
       2.704 , 2.7045, 2.705 , 2.7055, 2.706 , 2.7065, 2.707 , 2.7075,
       2.708 , 2.7085, 2.709 , 2.7095, 2.71  , 2.7105, 2.711 , 2.7115,
       2.712 , 2.7125, 2.713 , 2.7135, 2.714 , 2.7145, 2.715 , 2.7155,
       2.716 , 2.7165, 2.717 , 2.7175, 2.718 , 2.7185, 2.719 , 2.7195,
       2.72  , 2.7205, 2.721 , 2.7215, 2.722 , 2.7225, 2.723 , 2.7235,
       2.724 , 2.7245, 2.725 , 2.7255, 2.726 , 2.7265, 2.727 , 2.7275,
       2.728 , 2.7285, 2.729 , 2.7295, 2.73  , 2.7305, 2.731 , 2.7315,
       2.732 , 2.7325, 2.733 , 2.7335, 2.734 , 2.7345, 2.735 , 2.7355,
       2.736 , 2.7365, 2.737 , 2.7375, 2.738 , 2.7385, 2.739 , 2.7395,
       2.74  , 2.7405, 2.741 , 2.7415, 2.742 , 2.7425, 2.743 , 2.7435,
       2.744 , 2.7445, 2.745 , 2.7455, 2.746 , 2.7465, 2.747 , 2.7475,
       2.748 , 2.7485, 2.749 , 2.7495, 2.75  , 2.7505, 2.751 , 2.7515,
       2.752 , 2.7525, 2.753 , 2.7535, 2.754 , 2.7545, 2.755 , 2.7555,
       2.756 , 2.7565, 2.757 , 2.7575, 2.758 , 2.7585, 2.759 , 2.7595,
       2.76  , 2.7605, 2.761 , 2.7615, 2.762 , 2.7625, 2.763 , 2.7635,
       2.764 , 2.7645, 2.765 , 2.7655, 2.766 , 2.7665, 2.767 , 2.7675,
       2.768 , 2.7685, 2.769 , 2.7695, 2.77  , 2.7705, 2.771 , 2.7715,
       2.772 , 2.7725, 2.773 , 2.7735, 2.774 , 2.7745, 2.775 , 2.7755,
       2.776 , 2.7765, 2.777 , 2.7775, 2.778 , 2.7785, 2.779 , 2.7795,
       2.78  , 2.7805, 2.781 , 2.7815, 2.782 , 2.7825, 2.783 , 2.7835,
       2.784 , 2.7845, 2.785 , 2.7855, 2.786 , 2.7865, 2.787 , 2.7875,
       2.788 , 2.7885, 2.789 , 2.7895, 2.79  , 2.7905, 2.791 , 2.7915,
       2.792 , 2.7925, 2.793 , 2.7935, 2.794 , 2.7945, 2.795 , 2.7955,
       2.796 , 2.7965, 2.797 , 2.7975, 2.798 , 2.7985, 2.799 , 2.7995,
       2.8   , 2.8005, 2.801 , 2.8015, 2.802 , 2.8025, 2.803 , 2.8035,
       2.804 , 2.8045, 2.805 , 2.8055, 2.806 , 2.8065, 2.807 , 2.8075,
       2.808 , 2.8085, 2.809 , 2.8095, 2.81  , 2.8105, 2.811 , 2.8115,
       2.812 , 2.8125, 2.813 , 2.8135, 2.814 , 2.8145, 2.815 , 2.8155,
       2.816 , 2.8165, 2.817 , 2.8175, 2.818 , 2.8185, 2.819 , 2.8195,
       2.82  , 2.8205, 2.821 , 2.8215, 2.822 , 2.8225, 2.823 , 2.8235,
       2.824 , 2.8245, 2.825 , 2.8255, 2.826 , 2.8265, 2.827 , 2.8275,
       2.828 , 2.8285, 2.829 , 2.8295, 2.83  , 2.8305, 2.831 , 2.8315,
       2.832 , 2.8325, 2.833 , 2.8335, 2.834 , 2.8345, 2.835 , 2.8355,
       2.836 , 2.8365, 2.837 , 2.8375, 2.838 , 2.8385, 2.839 , 2.8395,
       2.84  , 2.8405, 2.841 , 2.8415, 2.842 , 2.8425, 2.843 , 2.8435,
       2.844 , 2.8445, 2.845 , 2.8455, 2.846 , 2.8465, 2.847 , 2.8475,
       2.848 , 2.8485, 2.849 , 2.8495, 2.85  , 2.8505, 2.851 , 2.8515,
       2.852 , 2.8525, 2.853 , 2.8535, 2.854 , 2.8545, 2.855 , 2.8555,
       2.856 , 2.8565, 2.857 , 2.8575, 2.858 , 2.8585, 2.859 , 2.8595,
       2.86  , 2.8605, 2.861 , 2.8615, 2.862 , 2.8625, 2.863 , 2.8635,
       2.864 , 2.8645, 2.865 , 2.8655, 2.866 , 2.8665, 2.867 , 2.8675,
       2.868 , 2.8685, 2.869 , 2.8695, 2.87  , 2.8705, 2.871 , 2.8715,
       2.872 , 2.8725, 2.873 , 2.8735, 2.874 , 2.8745, 2.875 , 2.8755,
       2.876 , 2.8765, 2.877 , 2.8775, 2.878 , 2.8785, 2.879 , 2.8795,
       2.88  , 2.8805, 2.881 , 2.8815, 2.882 , 2.8825, 2.883 , 2.8835,
       2.884 , 2.8845, 2.885 , 2.8855, 2.886 , 2.8865, 2.887 , 2.8875,
       2.888 , 2.8885, 2.889 , 2.8895, 2.89  , 2.8905, 2.891 , 2.8915,
       2.892 , 2.8925, 2.893 , 2.8935, 2.894 , 2.8945, 2.895 , 2.8955,
       2.896 , 2.8965, 2.897 , 2.8975, 2.898 , 2.8985, 2.899 , 2.8995,
       2.9   , 2.9005, 2.901 , 2.9015, 2.902 , 2.9025, 2.903 , 2.9035,
       2.904 , 2.9045, 2.905 , 2.9055, 2.906 , 2.9065, 2.907 , 2.9075,
       2.908 , 2.9085, 2.909 , 2.9095, 2.91  , 2.9105, 2.911 , 2.9115,
       2.912 , 2.9125, 2.913 , 2.9135, 2.914 , 2.9145, 2.915 , 2.9155,
       2.916 , 2.9165, 2.917 , 2.9175, 2.918 , 2.9185, 2.919 , 2.9195,
       2.92  , 2.9205, 2.921 , 2.9215, 2.922 , 2.9225, 2.923 , 2.9235,
       2.924 , 2.9245, 2.925 , 2.9255, 2.926 , 2.9265, 2.927 , 2.9275,
       2.928 , 2.9285, 2.929 , 2.9295, 2.93  , 2.9305, 2.931 , 2.9315,
       2.932 , 2.9325, 2.933 , 2.9335, 2.934 , 2.9345, 2.935 , 2.9355,
       2.936 , 2.9365, 2.937 , 2.9375, 2.938 , 2.9385, 2.939 , 2.9395,
       2.94  , 2.9405, 2.941 , 2.9415, 2.942 , 2.9425, 2.943 , 2.9435,
       2.944 , 2.9445, 2.945 , 2.9455, 2.946 , 2.9465, 2.947 , 2.9475,
       2.948 , 2.9485, 2.949 , 2.9495, 2.95  , 2.9505, 2.951 , 2.9515,
       2.952 , 2.9525, 2.953 , 2.9535, 2.954 , 2.9545, 2.955 , 2.9555,
       2.956 , 2.9565, 2.957 , 2.9575, 2.958 , 2.9585, 2.959 , 2.9595,
       2.96  , 2.9605, 2.961 , 2.9615, 2.962 , 2.9625, 2.963 , 2.9635,
       2.964 , 2.9645, 2.965 , 2.9655, 2.966 , 2.9665, 2.967 , 2.9675,
       2.968 , 2.9685, 2.969 , 2.9695, 2.97  , 2.9705, 2.971 , 2.9715,
       2.972 , 2.9725, 2.973 , 2.9735, 2.974 , 2.9745, 2.975 , 2.9755,
       2.976 , 2.9765, 2.977 , 2.9775, 2.978 , 2.9785, 2.979 , 2.9795,
       2.98  , 2.9805, 2.981 , 2.9815, 2.982 , 2.9825, 2.983 , 2.9835,
       2.984 , 2.9845, 2.985 , 2.9855, 2.986 , 2.9865, 2.987 , 2.9875,
       2.988 , 2.9885, 2.989 , 2.9895, 2.99  , 2.9905, 2.991 , 2.9915,
       2.992 , 2.9925, 2.993 , 2.9935, 2.994 , 2.9945, 2.995 , 2.9955,
       2.996 , 2.9965, 2.997 , 2.9975, 2.998 , 2.9985, 2.999 , 2.9995])

In [16]:
lassocv = LassoCV(alphas=alphas, cv=10, max_iter=100000)
lassocv.fit(X, y)
lassocv.alpha_

AxisError: axis -1 is out of bounds for array of dimension 0

In [17]:
lasso = Lasso(alpha = 0.5)
lasso.fit(X, y)

Lasso(alpha=0.5)

In [18]:
df2 = pd.DataFrame(np.random.rand(20,3), columns=['theta', 'alpha', 'beta'])
df2['parts'] = np.ones((20,), dtype=int) * 1500
df2

       theta     alpha      beta  parts
0   0.157990  0.884397  0.052992   1500
1   0.835804  0.588605  0.279788   1500
2   0.101562  0.762059  0.873422   1500
3   0.726001  0.531946  0.068834   1500
4   0.072865  0.850723  0.091960   1500
5   0.812670  0.375517  0.859019   1500
6   0.935480  0.609519  0.633093   1500
7   0.071821  0.318103  0.250535   1500
8   0.199030  0.415688  0.350647   1500
9   0.652712  0.304807  0.038603   1500
10  0.853798  0.645046  0.870128   1500
11  0.476530  0.529078  0.360257   1500
12  0.956826  0.939131  0.604971   1500
13  0.476319  0.041057  0.851781   1500
14  0.935848  0.873834  0.012339   1500
15  0.735119  0.839863  0.672735   1500
16  0.533666  0.893823  0.468967   1500
17  0.429502  0.260815  0.001257   1500
18  0.182974  0.080738  0.156906   1500
19  0.365819  0.248194  0.418754   1500

In [19]:
lasso_pred = lasso.predict(df2)
df3 = df2.copy()
df3['results'] = lasso_pred
df3

       theta     alpha      beta  parts      results
0   0.157990  0.884397  0.052992   1500  1663.619109
1   0.835804  0.588605  0.279788   1500  1658.102780
2   0.101562  0.762059  0.873422   1500  1648.435186
3   0.726001  0.531946  0.068834   1500  1653.238307
4   0.072865  0.850723  0.091960   1500  1659.120788
5   0.812670  0.375517  0.859019   1500  1639.324216
6   0.935480  0.609519  0.633093   1500  1659.357046
7   0.071821  0.318103  0.250535   1500  1622.484942
8   0.199030  0.415688  0.350647   1500  1631.255057
9   0.652712  0.304807  0.038603   1500  1636.600172
10  0.853798  0.645046  0.870128   1500  1658.172555
11  0.476530  0.529078  0.360257   1500  1645.208605
12  0.956826  0.939131  0.604971   1500  1682.023514
13  0.476319  0.041057  0.851781   1500  1609.246286
14  0.935848  0.873834  0.012339   1500  1681.309807
15  0.735119  0.839863  0.672735   1500  1669.771560
16  0.533666  0.893823  0.468967   1500  1670.097417
17  0.429502  0.260815  0.001257   1500  1628.730373
18  0.182974  0.080738  0.156906   1500  1609.901239
19  0.365819  0.248194  0.418754   1500  1623.498240